# Site settings
title: AVWOS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Only the best (worst?) in antivax insanity
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: https://avwos.github.io
github_username:  avwos

# Build settings
markdown: kramdown
highlighter: null
